WebService/Controllers/BuscarPedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebService.Core;
using WebService.ViewModel;
using WebService.Models;
using WebService.Enum;

namespace WebService.Controllers
{
    public class BuscarPedidoController : Controller
    {
        private static UInt32 _paginaAtual = 1;

        // GET: BuscarPedido
        public ActionResult BuscarPedido()
        {
            return View();
        }

        public ActionResult ListarPedidos(AcaoPaginacaoListagem.Paginacao? acao)
        {
            if (acao == null)
                acao = AcaoPaginacaoListagem.Paginacao.DEFAULT;

            if (acao == AcaoPaginacaoListagem.Paginacao.DEFAULT)
                _paginaAtual = 1;
            else if (acao == AcaoPaginacaoListagem.Paginacao.AVANCAR)
                _paginaAtual++;
            else if (acao == AcaoPaginacaoListagem.Paginacao.VOLTAR && _paginaAtual != 1)
                _paginaAtual--;

            PedidoWSCore pedidoWSCore = new PedidoWSCore();
            PedidosCompraModel lista = pedidoWSCore.GetPedidosPaginados(_paginaAtual);

            return View(lista);
        }
        
        public ActionResult DetalhaPedido(string numPc, AcaoDetalhamentoPedido.AcaoDetalhamentoPC acao)
        {
            PedidoCompraModel pc = null;
            
            try { 
                if (String.IsNullOrWhiteSpace(numPc)) return BuscarPedido();

                pc = new PedidoWSCore().GetPedido("01", "03", numPc, "0000"); // BUSCA A INFORMAÇÃO NO WEB SERVICE

                if (!pc.Equals(null))
                    pc.MsgLiberado = "";

                // FAZ AS VERIFICAÇÕES DE DIFERENTES TIPOS DE CHAMADAS DA TELA
                if (AcaoDetalhamentoPedido.AcaoDetalhamentoPC.APROVAR_PC_SUCESSO == acao)
                    pc.MsgLiberado = "Pedido Aprovado com Sucesso";
                else if (AcaoDetalhamentoPedido.AcaoDetalhamentoPC.APROVAR_PC_ERRO == acao)
                    pc.MsgLiberado = "Falha na Aprovação do Pedido, contate o administrador";
                else if (AcaoDetalhamentoPedido.AcaoDetalhamentoPC.REJEITAR_PC_SUCESSO == acao)
                    pc.MsgLiberado = "Pedido Rejeitado com Sucesso";
                else if (AcaoDetalhamentoPedido.AcaoDetalhamentoPC.REJEITAR_PC_ERRO == acao)
                    pc.MsgLiberado = "Falha na Rejeição do Pedido, contate o administrador";

                if (pc == null) return BuscarPedido();
            }catch(ArgumentNullException argument)
            {
                Console.WriteLine(argument.Message);
                return RedirectToAction("Index", "Home");
            }catch(Exception exception)
            {
                Console.WriteLine(exception.Message);
                return RedirectToAction("Index", "Home");
            }
                return View(pc);

        }
        
        


        [HttpPost]
        public ActionResult RejeitaPedido(string numPc)
        {
            if (String.IsNullOrWhiteSpace(numPc)) return BuscarPedido();

            PedidoWSCore pedidoWS = new PedidoWSCore();
            bool retorno = pedidoWS.RejeitaPedido(numPc);

            if (retorno)
                return DetalhaPedido(numPc, AcaoDetalhamentoPedido.AcaoDetalhamentoPC.REJEITAR_PC_SUCESSO);
            else
                return DetalhaPedido(numPc, AcaoDetalhamentoPedido.AcaoDetalhamentoPC.REJEITAR_PC_ERRO);
        }


        [HttpPost]
        public ActionResult LiberaPedido(string numPc)
        {
            if (String.IsNullOrWhiteSpace(numPc)) return BuscarPedido();
        
            PedidoWSCore pedidoWS = new PedidoWSCore();
            bool retorno = pedidoWS.LiberaPedido(numPc);

            if (retorno)
                return RedirectToAction("DetalhaPedido", new { numPc = numPc, acao = AcaoDetalhamentoPedido.AcaoDetalhamentoPC.APROVAR_PC_SUCESSO });
            else
                return RedirectToAction("DetalhaPedido", new { numPc = numPc, acao = AcaoDetalhamentoPedido.AcaoDetalhamentoPC.APROVAR_PC_ERRO });
            //return DetalhaPedido(numPc, AcaoDetalhamentoPedido.AcaoDetalhamentoPC.APROVAR_PC_ERRO);

        }
    }
}

WebService/Views/BuscarPedido/BuscarPedido.cshtml
@{
    ViewBag.Title = "Busca de Pedidos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Buscar Pedido</h1>

<div class="col-md-offset-4">
    @using (Html.BeginForm("DetalhaPedido", "BuscarPedido", FormMethod.Post))
    {
            <div class="form-group">
                <div class="col-md-2">
                    <label for="txtNumPc">Número do PC</label>
                </div>
                <input type="text" name="numPc" class="input-sm" placeholder="Digite o número do PC" />
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    <label for="txtNumFilial">Filial:</label>
                </div>
                <input type="text" class="input-sm" placeholder="Digite a Filial" />
            </div>

            <input type="text" hidden value="0" name="acao" />

            <input type="submit" class="btn btn-primary" value="Buscar" />
    }

</div>

<div id="lista">

</div>

WebService/Views/BuscarPedido/DetalhaPedido.cshtml
@model WebService.Models.PedidoCompraModel

@{
    ViewBag.Title = "DetalhaPedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Pedidos.js"></script>
<link href="~/Content/DetalhePedido.css" type="text/css" rel="stylesheet"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


<div id="corpo">

    <!-- PRIMEIRA LINHA -->
    <div class="row">

        <!-- LOGO -->

        <div class="col-sm-2">
            <img src="~/Content/Imagens/everest-logo.png" width="100" height="130" />
        </div>

        <!-- DADOS DO FORNECEDOR -->
        <div class="col-sm-7">

            <label>@Model.PCWS.A2_NOME</label>
            <br />

            @Html.Label("Endereço: ")
            @Html.DisplayFor(m => m.EnderecoCompleto)
            <br />

            @Html.Label("CEP: ")
            @Html.DisplayFor(fornecedor => fornecedor.PCWS.A2_CEP)
            <br />
            @Html.Label("CNPJ: ")
            @Html.DisplayFor(fornecedor => fornecedor.PCWS.A2_CGC)
            <br />
            @Html.Label("IE: ")
            @Html.DisplayFor(fornecedor => fornecedor.PCWS.A2_INSCR)
            <br />

        </div>

        <!-- PRIMEIRA LINHA, ULTIMO DA DIREITA -->
        <div class="col-sm-3">

            @Html.Label("Número: ")
            @Html.DisplayFor(fornecedor => fornecedor.PCWS.C7_NUM)
            <br />
            @Html.Label("Liberação: ")
            @Html.DisplayFor(fornecedor => fornecedor.Liberacao)
            <br />
            @Html.DisplayFor(fornecedor => fornecedor.PCWS.INFOSTATUS)
            <br />
            @Html.Label("Data Emissão: ")
            @Html.DisplayFor(fornecedor => fornecedor.DataEmissao)
            <br />
            @Html.Label("Solicitante: ")
            @*Html.DisplayFor(fornecedor => fornecedor.PCWS.CNOMEUSUARIO)*@
            <br />
            @Html.Label("Condicao de Pagamento")
            @Html.DisplayFor(fornecedor => fornecedor.CondicaoPagamento)
        </div>

    </div>

    <hr />
    @Html.Label("Dados Adicionais")

    <div class="row">

        <div class="col-sm-6">
            @Html.Label("Favorecido: ")
            @*Html.DisplayFor(fornecedor => fornecedor.PCWS.A2_FAVOREC)*@
            <br />
            @Html.Label("Fone: ")
            @Html.DisplayFor(fornecedor => fornecedor.PCWS.A2_TEL)
            <br />
        </div>

        <div class="col-sm-6">
            <!-- DADOS DO PC -->
            @Html.Label("Natureza: ")
            @*Html.DisplayFor(fornecedor => fornecedor.PCWS.C7_NATUR)*@
            <br />
            @Html.Label("Dados Bancários")
            @Html.DisplayFor(fornecedor => fornecedor.DadosBancarios)
            <br />
        </div>
    </div>

    <hr />

    <div class="table-responsive">
        <table class="table">
            <thead title="teste">
                <tr>
                    @foreach (var head in Model.PCWS.TBLPEDIDO.TABLESTRUCT)
                    {
                        <th>@head.FLDNAME</th>
                    }
                </tr>
            </thead>
            <tbody>

                @foreach (WebService.PedidoCompra.FIELDVIEW linha in Model.PCWS.TBLPEDIDO.TABLEDATA)
                {
                    <text>
                        <tr>
                            @foreach (var coluna in linha.FLDTAG)
                            {
                                <td>@coluna</td>
                            }
                        </tr>
                    </text>

                }


            </tbody>
        </table>
    </div>

    <hr />
    <!-- DETALHANDO VALORES -->
    <div class="row">

        <div class="col-md-8">
            <label class="text-danger">Observações</label>
            <label>
                @Model.PCWS.C7_OBSERV
            </label>
        </div>

        <div class="col-xs-12 col-md-4 ">
            <div class="table-responsive ">
                <table class="table" id="tabela-valores">
                    <tbody>

                        @if (Model.PCWS.NVALMERC != 0)
                        {
                            <tr>
                                <td>Valor dos Produtos</td>
                                <td id="thValProd">@Model.AjustaDinheiroBrasil(Model.PCWS.NVALMERC.ToString())</td>
                            </tr>
                        }
                        @if (Model.PCWS.NVALIPI != 0)
                        {
                            <tr>
                                <td>Valor de I.P.I</td>
                                <td id="thValIpi">@Model.AjustaDinheiroBrasil(Model.PCWS.NVALIPI.ToString())</td>
                            </tr>
                        }
                        @if (Model.PCWS.NVALDESC != 0)
                        {
                            <tr>
                                <td>Valor de Desconto</td>
                                <td id="thValDesc">@Model.AjustaDinheiroBrasil(Model.PCWS.NVALDESC.ToString())</td>
                            </tr>
                        }
                        @if (Model.PCWS.NTOTACR != 0)
                        {
                            <tr>
                                <td>Valor de Acréscimo</td>
                                <td id="thValAcresc">@Model.AjustaDinheiroBrasil(Model.PCWS.NTOTACR.ToString())</td>
                            </tr>
                        }
                        @if (Model.PCWS.NTOTSEG != 0)
                        {
                            <tr>
                                <td>Valor de Seguro</td>
                                <td id="thValSeg">@Model.AjustaDinheiroBrasil(Model.PCWS.NTOTSEG.ToString())</td>
                            </tr>
                        }
                        @if (Model.PCWS.NTOTFRE != 0)
                        {
                            <tr>
                                <td>Valor de Frete</td>
                                <td id="thValFrete">@Model.AjustaDinheiroBrasil(Model.PCWS.NTOTFRE.ToString())</td>
                            </tr>
                        }
                        @if (Model.PCWS.NTOTICMSRET != 0)
                        {
                            <tr>
                                <td>Valor de ICMS Retido</td>
                                <td id="thValICMS">@Model.AjustaDinheiroBrasil(Model.PCWS.NTOTICMSRET.ToString())</td>
                            </tr>
                        }
                        @if (Model.PCWS.NTOTAL != 0)
                        {
                            <tr>
                                <td class="alert-success">Valor Total</td>
                                <td id="thValTotal" class="alert-success">@Model.AjustaDinheiroBrasil(Model.PCWS.NTOTAL.ToString())</td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>


    <!-- HISTORICO DE APROVACOES -->
    <h2>Histórico de Aprovações</h2>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Aprovador</th>
                    <th>Nível</th>
                    <th>Data de Aprovação</th>
                    <th>Aprovado Por:</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var aprovador in Model.PCWS.LIBERACOES)
                {
                    <tr>
                        <text>
                            <td>@aprovador.APROVADOR</td>
                            <td>@aprovador.CR_NIVEL</td>
                            <td>@Model.AjusteData(aprovador.CR_DATALIB)</td>
                            <td>@aprovador.APROVADOPOR</td>
                        </text>
                    </tr>
                }


            </tbody>
        </table>
    </div>

    <label>@Model.MsgLiberado</label>
    <!-- BOTAO DE LIBERAÇÃO DE PEDIDOS -->

    <div id="botoes">
        <div class="row form-group">

            @using (Html.BeginForm("LiberaPedido", "BuscarPedido", FormMethod.Post))
            {
                if (Model.Liberacao.Equals("Pendente"))
                {
                    <input type="text" hidden name="numPc" value="@Model.PCWS.C7_NUM" />
                    <button class="btn btn-success">Aprovar</button>
                }
            }
        </div>

        <div class="row form-group">


            @using (Html.BeginForm("RejeitaPedido", "BuscarPedido", FormMethod.Post))
            {
                if (Model.Liberacao.Equals("Pendente"))
                {
                    <input type="text" hidden name="numPc" value="@Model.PCWS.C7_NUM" />
                    <button class="btn btn-danger">Rejeitar</button>
                }
            }
        </div>
    </div>
    @if (!Model.MsgLiberado.Equals(""))
    {
        <div class="alert-info">
            <label id="msg-acoes"></label>
        </div>
    }


</div>

WebService/Views/BuscarPedido/ListarPedidos.cshtml
@model WebService.Models.PedidosCompraModel

@{
    ViewBag.Title = "ListarPedidos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<link href="~/Content/ListarPedidos.css" type="text/css" rel="stylesheet" />

<div id="corpo">

    <div id="titulo">
     
        <h1>Pedidos de Compra</h1>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Número do PC</th>
                    <th>Fornecedor</th>
                    <th>Comprador</th>
                    <th>Emissão</th>
                    <th>Valor</th>
                    <th>Liberar</th>
                    <th>Rejeitar</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var pedido in Model._pedidos)
            {
                <text>
                    <tr>
                        <td>@pedido.CR_NUM</td>
                        <td>@pedido.A2_NOME</td>
                        <td>@pedido.COMPRADOR</td>
                        <td>@Model.AjusteData(pedido.CR_EMISSAO)</td>
                        <td>@Model.AjusteDinheiroBrasil(pedido.CR_TOTAL)</td>
                        <td><button class="btn btn-success">Liberar</button></td>
                        <td><button class="btn btn-danger">Rejeitar</button></td>
                    </tr>
                </text>
        }

            </tbody>

        </table>


        <nav aria-label="Navegação de página" id="navegacao-paginas">

            <div id="linha">
                
                <div id="esquerda">
                    <!-- ANTERIOR -->
                    @using (Html.BeginForm("ListarPedidos", "BuscarPedido", FormMethod.Post))
                    {
                            <text>
                                <input type="text" value="2" name="acao" hidden />
                                <button class="btn btn-default">Anterior</button>
                            </text>
                    }
                </div>
                <div id="direita">
                    <!-- PROXIMO -->
                    @using (Html.BeginForm("ListarPedidos", "BuscarPedido", FormMethod.Post))
                    {
                                <text>
                                    <input type="text" name="acao" value="1" hidden />
                                    <button class="btn btn-primary" type="submit">Próximo</button>
                                </text>
                    }
                </div>
           </div>
        </nav>


    </div>



</div>